import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import {
  QuantizerCelebi,
  Score,
  argbFromRgb,
  hexFromArgb,
} from '@material/material-color-utilities';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const siteConfigPath = path.join(projectRoot, 'assets', 'site.json');
const generatedThemeCssPath = path.join(projectRoot, 'target', 'material-theme.css');
const fallbackSourceColor = '#536b73';

function fail(message) {
  throw new Error(`[material-theme] ${message}`);
}

function assertLocalAssetPath(assetPath) {
  if (typeof assetPath !== 'string' || assetPath.trim() === '') {
    fail('site.json must define a non-empty theme.background path.');
  }

  if (/^[a-z][a-z\d+.-]*:/i.test(assetPath) || assetPath.startsWith('//')) {
    fail(`theme.background must be a local asset path, received: ${assetPath}`);
  }

  const assetsRoot = path.resolve(projectRoot, 'assets');
  const absolutePath = path.resolve(assetsRoot, assetPath.replace(/^[/\\]+/, ''));
  if (absolutePath !== assetsRoot && !absolutePath.startsWith(`${assetsRoot}${path.sep}`)) {
    fail(`theme.background escapes the assets directory: ${assetPath}`);
  }

  return absolutePath;
}

async function readBackgroundPath() {
  let siteConfig;
  try {
    siteConfig = JSON.parse(await fs.readFile(siteConfigPath, 'utf8'));
  } catch (error) {
    fail(`could not read ${path.relative(projectRoot, siteConfigPath)}: ${error.message}`);
  }

  return assertLocalAssetPath(siteConfig?.theme?.background);
}

async function extractSourceColor(imagePath) {
  let decoded;
  try {
    decoded = await sharp(imagePath)
      .resize({ width: 96, height: 96, fit: 'inside', withoutEnlargement: true })
      .removeAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
  } catch (error) {
    fail(`could not decode ${path.relative(projectRoot, imagePath)}: ${error.message}`);
  }

  const pixels = [];
  for (let offset = 0; offset < decoded.data.length; offset += decoded.info.channels) {
    pixels.push(argbFromRgb(
      decoded.data[offset],
      decoded.data[offset + 1],
      decoded.data[offset + 2],
    ));
  }

  if (pixels.length === 0) {
    fail(`the configured background contains no readable pixels: ${imagePath}`);
  }

  // The JavaScript implementation of Celebi's weighted k-means uses
  // Math.random() for its initial point assignments. Seed that small section
  // explicitly so identical source pixels produce identical CI CSS.
  const nativeRandom = Math.random;
  let randomState = 0x6d2b79f5;
  Math.random = () => {
    randomState = Math.imul(1664525, randomState) + 1013904223;
    return (randomState >>> 0) / 0x100000000;
  };

  let rankedColors;
  try {
    rankedColors = Score.score(QuantizerCelebi.quantize(pixels, 128));
  } finally {
    Math.random = nativeRandom;
  }
  return rankedColors[0] ?? null;
}

const backgroundPath = await readBackgroundPath();
const extractedColor = await extractSourceColor(backgroundPath);
const sourceColor = extractedColor === null ? fallbackSourceColor : hexFromArgb(extractedColor);

await fs.mkdir(path.dirname(generatedThemeCssPath), { recursive: true });
await fs.writeFile(
  generatedThemeCssPath,
  `/* Generated by scripts/generate_material_theme.mjs. Do not edit. */\n@layer base {\n  :root {\n    --material-source-color: ${sourceColor};\n  }\n}\n`,
  'utf8',
);

console.log(`[material-theme] ${path.relative(projectRoot, backgroundPath)} → ${sourceColor}`);
